/* Generated by build_gallery.py. Edit entries here after generation if needed. */
window.ARTWORKS = [
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (1).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (1)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (2).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (2)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (3).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (3)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (4).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (4)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (5).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (5)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (6).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (6)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (7).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (7)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (8).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (8)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (9).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (9)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (10).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (10)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (11).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (11)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (12).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (12)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (13).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (13)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (14).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (14)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (15).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (15)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (16).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (16)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM (17).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm (17)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.02 PM.jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.02 Pm",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (1).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (1)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (2).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (2)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (3).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (3)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (4).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (4)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (5).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (5)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (6).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (6)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (7).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (7)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (8).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (8)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (9).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (9)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (10).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (10)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (11).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (11)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (12).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (12)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (13).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (13)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (14).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (14)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (15).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (15)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (16).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (16)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (17).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (17)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (18).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (18)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (19).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (19)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (20).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (20)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (21).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (21)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (22).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (22)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (23).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (23)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (24).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (24)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (25).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (25)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (26).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (26)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (27).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (27)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (28).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (28)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (29).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (29)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (30).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (30)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM (31).jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm (31)",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  },
  {
    "src": "images/paintings/WhatsApp Image 2026-07-16 at 1.07.03 PM.jpeg",
    "title": "Whatsapp Image 2026 07 16 At 1.07.03 Pm",
    "category": "Flowers",
    "medium": "Watercolour & ink",
    "year": ""
  }
];
