"""Build artworks.js from the contents of images/paintings.

Usage from the website folder:
    python build_gallery.py

Accepted image types: jpg, jpeg, png, webp, gif, avif, heic, heif, svg
Note: HEIC/HEIF browser support is inconsistent. Converting those files to JPG or
WebP before publishing is recommended.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
IMAGE_DIR = ROOT / "images" / "paintings"
OUTPUT = ROOT / "artworks.js"
VALID_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".heic", ".heif", ".svg"}
PLACEHOLDER_PREFIX = "placeholder-"


def natural_key(path: Path) -> list[object]:
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", path.name)]


def title_from_filename(path: Path) -> str:
    title = re.sub(r"[_-]+", " ", path.stem)
    title = re.sub(r"\s+", " ", title).strip()
    return title.title() or "Untitled"


def main() -> None:
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    files = sorted(
        (path for path in IMAGE_DIR.rglob("*") if path.is_file() and path.suffix.lower() in VALID_EXTENSIONS),
        key=natural_key,
    )

    real_files = [path for path in files if not path.name.lower().startswith(PLACEHOLDER_PREFIX)]
    if not real_files:
        print("No non-placeholder images were found. Add your paintings and run the script again.")
        print(f"Left the existing {OUTPUT.name} unchanged.")
        return

    artworks = []
    for path in real_files:
        relative = path.relative_to(ROOT).as_posix()
        artworks.append(
            {
                "src": relative,
                "title": title_from_filename(path),
                "category": "Flowers",
                "medium": "Watercolour & ink",
                "year": "",
            }
        )

    payload = json.dumps(artworks, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "/* Generated by build_gallery.py. Edit entries here after generation if needed. */\n"
        f"window.ARTWORKS = {payload};\n",
        encoding="utf-8",
    )

    print(f"Added {len(artworks)} artwork(s) to {OUTPUT.name}.")


if __name__ == "__main__":
    main()
